title: "KCC"
site_name: KCC Gem Theme
public-url: "https://www.kcc.edu"
url: 'URL is needed for robots.txt to work properly' ## NO TRAILING SLASHES!!/<--nope
canonical_baseurl: https://www.kcc.edu # NO trailing slash ## Used to build canonical link elements in document head
port: 3000
timezone: America/Chicago
google-tag_key: Google Tag Manager key goes here
theme_config: true # This key should only be in the theme's _config.yml file and nowhere else # Otherwise you will get JS errors
core_site: true
# translate: true ## Uncomment to activate Google Translate Powers (unfortunately no cowpowers)!!
collections:
  tabs:
    output: false
  accordions:
    output: false
  contacts:
    output: false
permalink: pretty
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
#include:
#  - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

# include:
  # - "_accordions/"
  # - "_tabs/"

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE.txt"
  - "webpack.config.js"
  - "*.gem"
  - "*.gemspec"
  - "ruby-version.txt"
  - "buildtools/"
  - "postcss.config.js"
  - "notes-on-bs5-migration.md"
  - "look-for-deprecated-bs4-classes.mjs"
  - "look-for-deprecated-bs4-js.mjs"
  - "look-for-string-in-project-files.mjs"

uploads_dir: # specifies the default uploads directory for uploads in CloudCannon
  - "uploads/"

## ================================================ ##
## Global/Main Navigation configuration for kcc.edu ##
## ================================================ ##
navigation: ## Add a navigation key to any project using kcc-gem-theme to locally override these settings
  - link_text: Academics # @link_text becomes the main navigational categories
    link_href: 'academics'
    image: # The image element built into each dropdown menu
      source: 'assets/img/menu-academics.jpg' # Points to the image file
      # YOU ALWAYS NEED ALT TEXT!!!
      alt: >-
        Student in an electrical technology lab standing 
        in front of electrical equipment mounted to a wall
    dropdown: # Defines the 'academics' items in the dropdown
## IMPORTANT: The first item in the 'dropdown' list is not sorted but stays as the first dropdown item...
##            After the first item, the dropdown list is sorted alphabetically by the 'text' key.
      - text: Academic Programs Home ## Text for the first dropdown item (stays at the top)
        href: 'academics' ## Relative link that the first dropdown item should point to
      - text: Class Schedule 
        href: 'schedule' # Relative link with hashes and queries work too 'page/#hash' or 'page/?id=some-heading#hash'
      - text: Academic Calendar
        href: 'calendar'
      - text: Continuing Education
        href: 'https://continuinged.kcc.edu/' ## Absolute URL with protocol works too
      - text: Illinois High School Diploma (GED)
        href: 'https://adulted.kcc.edu/programs/ged/'
      - text: Commencement
        href: 'commencement'
      - text: Final Exam Schedule
        href: 'final-exams'
      - text: Register for Classes
        href: 'register'
      - text: Academic Catalog
        href: 'https://kcc.smartcatalogiq.com/current/Academic-Catalog'
      - text: "Exam Make-ups"
        href: exam-makeups
## Admissions ##
  - link_text:  Admissions
    link_href: admissions
    image:
      source: 'assets/img/menu-admission.jpg'
      alt: 'Smiling student inside the KCC main entrance'
    dropdown:
      - text:  Admissions Home
        href: admissions
      - text: Placement Testing
        href: 'testing'
      - text: Apply
        href: 'https://apply.kcc.edu'
      - text: Request Information
        href: 'https://info.kcc.edu/'
      - text: Visit/Explore
        href: 'https://visit.kcc.edu'
      - text: 'Start in High School'
        href: 'high-school'
      - text: Request KCC Transcripts
        href: '#request-your-transcript'
      - text: 'Veterans Services'
        href: 'veterans'
      - text: 'Credit for Prior Learning'
        href: 'credit-for-prior-learning'
## Tuition & Aid
  - link_text:  Tuition & Aid
    link_href: 'tuition-and-aid'
    image:
      source: 'assets/img/menu_fafsa-early-bird-web-banner-23.jpg'
      alt: >-
        The early bird gets the money. FAFSA available before Dec. 31. Apply at fafsa.gov.
        More details and workshop info at www.kcc.edu/finaid
    dropdown:
      - text:  Tuition & Aid Home
        href: 'tuition-and-aid'
      - text: Financial Aid
        href: 'financial-aid'
      - text: Net Price Calculator
        href: 'net-price-calculator'
      - text: 'Cost to Attend KCC'
        href: '#cost-to-attend'
      - text: 'Tuition Payment & Deadlines'
        href: '#tuition-payment-and-deadlines'
      - text: 'Financial Aid Forms'
        href: 'financial-aid/#financial-aid-forms'
      - text: 'Student Employment'
        href: 'financial-aid/#student-employment'
## Student Resources ##
  - link_text: Student Resources
    link_href: 'student-resources'
    image:
      source: 'assets/img/menu-student-resources.jpg'
      alt: >-
        KCC Veteran Services staff from left-to-right; 
        Kendra Souligne, Hassel Hernandez, Jason Rodriguez, 
        and Megan Ponton.
    dropdown:
      - text: Student Resources Home
        href: 'student-resources'
      - text: Bookstore
        href: 'https://books.kcc.edu'
      - text: Clubs & Organizations
        href: 'clubs'
      - text: 'Center for Equity, Diversity & Inclusion'
        href: 'edi'
      - text: Fitness Center
        href: 'https://athletics.kcc.edu/facilities/fitness-center'
      - text: Advising
        href: 'advising'
      - text: Transfer Services
        href: 'transfer'
      - text: 'Counseling & Referral Services'
        href: 'counseling-and-referral-services'
      - text: Disability Services
        href: 'disability-services'
      - text: Student Representatives
        href: 'student-representatives'
      - text: Student Complaint Policy
        href: 'student-complaint-policy'
      - text: Start the Semester Right
        href: 'welcome'
      - text: KCC Food Pantry
        href: 'food-pantry'
      - text: Tutoring
        href: 'https://library.kcc.edu/tutoring/'
      - text: TRIO Student Support Services
        href: 'trio'
      - text: Career Services
        href: 'career-services'
      - text: Food Services
        href: 'food-services'
      - text: Workforce Services
        href: 'https://wioa.kcc.edu/'
      - text: Student Handbook
        href: handbook
      - text: Support Resources
        href: support-resources
      - text: Student Life Events Calendar
        href: events-calendar
## Community ##
  - link_text: Community
    link_href: 'community'
    image:
      source: 'assets/img/menu-community.jpg'
      alt: 'The Criminal Justice Club posing on the metal sculpture in front of the KCC main entrance'
    dropdown:
      - text: Community Home
        href: 'community'
      - text: Adult & Community Education
        href: 'https://adulted.kcc.edu/'
      - text: Continuing Education
        href: 'https://continuinged.kcc.edu'
      - text: Sustainability
        href: 'sustainability'
      - text: Arts & Culture
        href: 'arts-and-culture'
      - text: Workforce Services
        href: 'https://wioa.kcc.edu/'
      - text: Community Testing Center
        href: testing-center
      - text: Wheels of Opportunity
        href: 'wheels'
## About KCC ##
  - link_text: About KCC
    link_href: 'about'
    link_nav: 'about'
    image:
      source: 'assets/img/menu-about-kcc.jpg'
      alt: 'Two students posing in front of the KCC main entrance'
    dropdown:
      - text: About KCC Home
        href: 'about'
      - text: Newsroom
        href: 'https://news.kcc.edu'
      - text: Leadership
        href: 'leadership'
      - text: Board of Trustees
        href: board-of-trustees
      - text: Human Resources
        href: 'human-resources'
      - text: Job Openings
        href: 'human-resources/job-openings'
      - text: Directories
        href: 'directories'
      - text: Information Technology Services
        href: 'its'
      - text: Marketing
        href: 'marketing'
      - text: 'Institutional Effectiveness'
        href: 'institutional-effectiveness'
      - text: 'Police & Safety'
        href: 'police-and-safety'
      - text: 'Student Code of Conduct'
        href: 'code-of-conduct'
      - text: 'Title IX'
        href: 'title-ix'
      - text: 'Contact Us'
        href: 'contact-us'
      - text: Web Services
        href: 'marketing/web-services'
      - text: Consumer Info and Disclosures
        href: 'consumer-info'
      - text: ICCB Salary and Benefits Portal
        href: 'https://iccbdbsrv.iccb.org/salarysearch/home.cfm'
      - text: COVID-19 Response
        href: 'https://coronavirus.kcc.edu'
