title: "KCC"
site_name: KCC Gem Theme
public-url: "https://www.kcc.edu"
url: 'URL is needed for robots.txt to work properly' ## NO TRAILING SLASHES!!/<--nope
google-tag_key: Google Tag Manager key goes here
core_site: true
#translate: true ## Uncomment to activate Google Translate Powers (unfortunately no cowpowers)!!
global_nav:
  - link_text: Academics
    image:
      source: 'uploads/e-tech_a-roberts_mar2016_D41_6690.jpg'
      alt: 'Student working in an electrical technology lab'
    dropdown:
      - text: Action
        href: '#'
      - text: Another action
        href: '#'
      - text: dropdown-divider
      - text: Something else here
        href: '#'
  - link_text:  Admission
    image:
      source: 'uploads/2016-senior-viewbook.jpg'
      alt: 'Take the first step to achieveing your goals, dreams & ambitions'
    dropdown:
      - text: Action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: dropdown-divider
      - text: Something else here
        href: '#'
  - link_text:  Tuition & Aid
    image:
      source: 'uploads/fafsa-early-bird-banner-18.jpg'
      alt: 'The early bird gets the money. FAFSA available Oct. 1. Apply at fafsa.gov. More details and workshop info at www.kcc.edu/finaid'
    dropdown:
      - text: Action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: dropdown-divider
      - text: Something else here
        href: '#'
  - link_text: Student Resources
    image:
      source: 'uploads/DSC_5650_helpful.jpg'
      alt: 'Receptionist answering the phone'
    dropdown:
      - text: Action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: dropdown-divider
      - text: Something else here
        href: '#'
  - link_text: Community
    image:
      source: 'uploads/go_cavs_20171002_193828-web.jpg'
      alt: 'Group photo of students holding Cavalier signs'
    dropdown:
      - text: Action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: dropdown-divider
      - text: Something else here
        href: '#'
  - link_text: About
    image:
      source: 'uploads/ATEC-DSC_1033.jpeg'
      alt: 'The new Advanced Technology Education Center building'
    dropdown:
      - text: Action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: Another action
        href: '#'
      - text: dropdown-divider
      - text: Something else here
        href: '#'

nav_links:
  - link_text: Home
    link_href: ''
    button: false
  - link_text: Landing Page
    link_href: 'landing-page'
    button: false
  - link_text: accordion
    link_href: 'accordion'
    button: false
  - link_text: Global Nav
    link_href: 'global-nav'
    button: false
  - link_text: Enroll
    dropdown:
      - text: Community Literacy
        href: 'programs/community-literacy'
      - text: English as a Second Language
        href: 'programs/esl'
      - text: GED/High School Equivalency
        href: 'programs/ged'
#  - link_text: Example External Link
#    link_href: 'https://example-external-link.com'
#    button: false
#    external: true  <---- #### Add the `external: true` key & value to make an external link ####
#
#### Example sub-nav configuration below #### =============================================================== #
##                                                                                                           ##
##   `link_href:` values must have a single '/' in the link (no '/' in the begining or end of the string)    ##
##                                                                                                           ##
## ========================================================================================================== #
#
#sub-nav_links:
#  - link_text: Sheets
#    link_href: 'reference/gsheets'
#  - link_text: CloudCannon
#    link_href: 'reference/cloudcannon'
#
collections:
  posts:
    _hide_content: true
  tabbed_nav:
    output: false
  accordions:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
permalink: pretty
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
#include:
#  - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "LICENSE.txt"
  - "webpack.config.js"
  - "*.gem"
  - "*.gemspec"
  - "gulp-tasks/"
  - "install.sh"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  description: "Descriptions are seen by search engines like Google and displayed in search results"
