title: "KCC"
site_name: KCC Gem Theme
public-url: "https://www.kcc.edu"
url: 'URL is needed for robots.txt to work properly' ## NO TRAILING SLASHES!!/<--nope
canonical_baseurl: https://www.kcc.edu # NO trailing slash ## Used to build canonical link elements in document head
port: 3000
timezone: America/Chicago
google-tag_key: Google Tag Manager key goes here
theme_config: true # This key should only be in the theme's _config.yml file and nowhere else # Otherwise you will get JS errors
core_site: true # Do not push or publish the theme with `core_site: false` (however, projects that use the gem should use `core_site: false` in their `_config.yml`)
# translate: true ## Uncomment to activate Google Translate Powers (unfortunately no cowpowers)!!
collections:
  tabs:
    output: false
  accordions:
    output: false
  contacts:
    output: false
permalink: pretty
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
#include:
#  - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

# include:
  # - "_accordions/"
  # - "_tabs/"

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE.txt"
  - "webpack.config.js"
  - "*.gem"
  - "*.gemspec"
  - "ruby-version.txt"
  - "buildtools/"
  - "postcss.config.js"
  - "pa11y.sh"
  - "pa11y.*.json"
  - "pa11y-log.*.txt"
  - "notes-on-bs5-migration.md"
  - "look-for-deprecated-bs4-classes.mjs"
  - "look-for-deprecated-bs4-js.mjs"
  - "look-for-string-in-project-files.mjs"
  - "look-for-string.mjs"

# Settings for the compress.html layout
## See https://jch.penibelst.de/ for more info
compress_html:
  clippings: all           # Array of elements to clip whitespace around or `all`
  comments: all            # Comments to strip out
  endings: all             # Array of elements with optional end tags or `all`
  ignore:
    envs: ['development']  # Array of environments to not compress in (from JEKYLL_ENV)
  # startings: [head, body]  # Array of elements with optional start tags
  # profile: true            # Generate a table of compression/savings stats

uploads_dir: # specifies the default uploads directory for uploads in CloudCannon
  - "uploads/"

# Hide page.schema_json_partial setting from CloudCannon
## Non-developers should never touch this setting!
_inputs:
  schema_json_partial:
    hidden: true

## ================================================ ##
## Global/Main Navigation configuration for kcc.edu ##
## ================================================ ##
navigation: ## Add a navigation key to any project using kcc-gem-theme to locally override these settings
  - link_text: Academics # @link_text becomes the main navigational categories
    link_href: 'academics'
    image: # The image element built into each dropdown menu
      source: 'assets/img/menu-academics.jpg' # Points to the image file
      # YOU ALWAYS NEED ALT TEXT!!!
      alt: >-
        Student in an electrical technology lab standing 
        in front of electrical equipment mounted to a wall
    button:
      text: 'Explore Program Pathways'
      href: '/academics/'
    dropdown: # Defines the 'academics' items in the dropdown
## IMPORTANT: The first item in the 'dropdown' list is not sorted but stays as the first dropdown item...
##            After the first item, the dropdown list is sorted alphabetically by the 'text' key.
      - text: Academic Programs Home ## Text for the first dropdown item (stays at the top)
        href: 'academics/' ## Relative link that the first dropdown item should point to
      - text: Class Schedule 
        href: 'schedule/' # Relative link with hashes and queries work too 'page/#hash' or 'page/?id=some-heading#hash'
      - text: Academic Calendar
        href: 'calendar/'
      - text: Continuing Education
        href: 'https://www.kcc.edu/continuinged/' ## Absolute URL with protocol works too
      - text: Illinois High School Diploma (GED)
        href: 'https://www.kcc.edu/adulted/programs/ged/'
      - text: Commencement
        href: 'commencement/'
      - text: Final Exam Schedule
        href: 'final-exams/'
      - text: Register for Classes
        href: 'register/'
      - text: Academic Catalog
        href: 'https://catalog.kcc.edu/'
      - text: "Exam Make-ups"
        href: exam-makeups/
      - text: "Online Learning"
        href: online-learning/
## Admissions ##
  - link_text:  Admissions
    link_href: admissions
    image:
      source: 'assets/img/menu-admission.jpg'
      alt: 'Smiling student inside the KCC main entrance'
    dropdown:
      - text:  Admissions Home
        href: admissions/
      - text: Placement Testing
        href: 'testing/'
      - text: Apply
        href: 'https://apply.kcc.edu'
      - text: Request Information
        href: 'https://info.kcc.edu/'
      - text: Visit/Explore
        href: 'https://visit.kcc.edu'
      - text: 'Start in High School'
        href: 'high-school/'
      - text: Request KCC Transcripts
        href: '#request-your-transcript'
      - text: 'Veterans Services'
        href: 'veterans/'
      - text: 'Credit for Prior Learning'
        href: 'credit-for-prior-learning/'
      - text: DACA/Undocumented Students
        href: 'undocumented/'
      - text: 'Health Careers Requirements'
        href: 'health-careers-requirements/'
## Tuition & Aid
  - link_text:  Tuition & Aid
    link_href: 'tuition-and-aid'
    image:
      source: 'assets/img/menu_fafsa-early-bird-web-banner-23.jpg'
      alt: >-
        The early bird gets the money. FAFSA available before Dec. 31. Apply at fafsa.gov.
        More details and workshop info at www.kcc.edu/finaid
    button:
      text: 'Financial Support Opportunities'
      href: '/tuition-and-aid/financial-support/'
    dropdown:
      - text:  Tuition & Aid Home
        href: 'tuition-and-aid/'
      - text: Financial Aid
        href: 'financial-aid/'
      - text: Net Price Calculator
        href: 'net-price-calculator/'
      - text: 'Cost to Attend KCC'
        href: '#cost-to-attend'
      - text: 'Tuition Payment & Deadlines'
        href: '#tuition-payment-and-deadlines'
      - text: 'Financial Aid Forms'
        href: 'financial-aid/#financial-aid-forms'
      - text: 'Student Employment'
        href: 'financial-aid/#student-employment'
## Student Resources ##
  - link_text: Student Resources
    link_href: 'student-resources'
    image:
      source: 'assets/img/menu-student-resources.jpg'
      alt: >-
        KCC Veteran Services staff from left-to-right; 
        Kendra Souligne, Hassel Hernandez, Jason Rodriguez, 
        and Megan Ponton.
    dropdown:
      - text: Student Resources Home
        href: 'student-resources/'
      - text: Bookstore
        href: 'https://books.kcc.edu'
      - text: 'Center for Equity, Diversity & Inclusion'
        href: 'edi/'
      - text: Fitness Center
        href: 'https://athletics.kcc.edu/facilities/fitness-center/'
      - text: Advising
        href: 'advising/'
      - text: Transfer Services
        href: 'transfer/'
      - text: 'Counseling & Referral Services'
        href: 'counseling-and-referral-services/'
      - text: Office of Disability Services
        href: 'disability-services/'
      - text: Start the Semester Right
        href: 'welcome/'
      - text: Tutoring
        href: 'https://www.kcc.edu/library/tutoring/'
      - text: TRIO Student Support Services
        href: 'trio/'
      - text: Career Services
        href: 'career-services/'
      - text: Food Services
        href: 'food-services/'
      - text: Workforce Services
        href: 'https://www.kcc.edu/workforceservices/'
      - text: Support Resources
        href: support-resources/
      - text: Student Life
        href: student-life/
## Community ##
  - link_text: Community
    link_href: 'community'
    image:
      source: 'assets/img/menu-community.jpg'
      alt: 'The Criminal Justice Club posing on the metal sculpture in front of the KCC main entrance'
    dropdown:
      - text: Community Home
        href: 'community/'
      - text: Adult & Community Education
        href: 'https://www.kcc.edu/adulted/'
      - text: Continuing Education
        href: 'https://www.kcc.edu/continuinged/'
      - text: Sustainability
        href: 'sustainability/'
      - text: Arts & Culture
        href: 'arts-and-culture/'
      - text: Workforce Services
        href: 'https://www.kcc.edu/workforceservices/'
      - text: Community Testing Center
        href: testing-center/
      - text: Wheels of Opportunity
        href: 'wheels/'
      - text: Giving
        href: 'https://www.kcc.edu/foundation/'
      - text: 'CEJA Workforce Hub'
        href: 'ceja/'
## About KCC ##
  - link_text: About KCC
    link_href: 'about'
    link_nav: 'about'
    image:
      source: 'assets/img/menu-about-kcc.jpg'
      alt: 'Two students posing in front of the KCC main entrance'
    dropdown:
      - text: About KCC Home
        href: 'about/'
      - text: Newsroom
        href: 'https://news.kcc.edu'
      - text: Leadership
        href: 'leadership/'
      - text: Board of Trustees
        href: board-of-trustees/
      - text: Human Resources
        href: 'human-resources/'
      - text: Job Openings
        href: 'human-resources/job-openings/'
      - text: Directories
        href: 'directories/'
      - text: Information Technology Services
        href: 'its/'
      - text: Marketing
        href: 'marketing/'
      - text: 'Institutional Effectiveness'
        href: 'institutional-effectiveness/'
      - text: 'Police & Safety'
        href: 'police-and-safety/'
      - text: 'Student Code of Conduct'
        href: 'code-of-conduct/'
      - text: 'Title IX'
        href: 'title-ix/'
      - text: 'Contact Us'
        href: 'contact-us/'
      - text: Web Services
        href: 'marketing/web-services/'
      - text: Consumer Info and Disclosures
        href: 'consumer-info/'
      - text: ICCB Salary and Benefits Portal
        href: 'https://iccbdbsrv.iccb.org/salarysearch/home.cfm'
      - text: COVID-19 Response
        href: 'https://coronavirus.kcc.edu'
      - text: Report a Concern
        href: 'report-a-concern/'
      - text: Freedom of Information
        href: 'https://www.kcc.edu/about/uploads/docs/freedom-of-information-act.pdf'

## =================================================================== ##
##  Local Nav and Sub Nav configuration for testing those components.  ##
##         Do not publish Local or Sub nav configuration...            ##
##         ...comment-out prior to pushing                             ##
## =================================================================== ##
### Set `core_site: false` (above) to test local and sub nav (navigate to /events/ page) ##
# nav_links:
#   - link_text: About
#     link_href: 'about/'
#     button: false
#   - link_text: Events
#     link_href: 'events/'
#     button: false
#   - link_text: Alumni
#     link_href: 'alumni/'
#     button: false
#   - link_text: Scholarships
#     link_href: 'scholarships/'
#     button: false
#   - link_text: Contact
#     link_href: '#contact'
#     button: false
#   - link_text: Give
#     link_href: 'give/'
#     button: true
### This is just an example for configuring an external link: ###
# #  - link_text: Example External Link
# #    link_href: 'https://example-external-link.com'
# #    button: false
# #    external: true  <---- #### Add the `external: true` key & value to make an external link ####
# sub-nav_links:
#   - link_text: 'Foundation Board'
#     link_href: 'about/foundation-board'
#   - link_text: "President's Circle Dinner"
#     link_href: 'events/presidents-circle-dinner/'
#   - link_text: "Women's Giving Circle"
#     link_href: 'events/womens-giving-circle'
#   - link_text: Alumni Event
#     link_href: 'events/alumni-event'
#   - link_text: 'Distinguished Alumni Award'
#     link_href: 'alumni/distinguished-alumni-award/'
#   - link_text: 'Alumni Stories'
#     link_href: 'alumni/alumni-stories/'
#   - link_text: 'Staff/Retiree Alumni Stories'
#     link_href: 'alumni/staff-stories/'
#   - link_text: 'Century Scholars'
#     link_href: 'scholarships/century-scholars/'
#   - link_text: 'Create a Scholarship'
#     link_href: scholarships/create-a-scholarship/
#   - link_text: "Employee Giving"
#     link_href: 'give/employee-giving/'
#   - link_text: "Planned Giving"
#     link_href: 'give/planned-giving/'
#   - link_text: "President's Circle"
#     link_href: 'give/presidents-circle/'
#   - link_text: "Women's Giving Circle"
#     link_href: 'give/womens-giving-circle/'
