# Configurations used in the gulpfile.js
browsersync:
  notify: true
  open:   false # set to true to open localhost:3000 in chrome browser upon execution of gulp command.
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

# Clean the jekyll _site/ build dir.
clean:
  - "_site" # clean these folders on execution of gulp command
#  - "_posts/*"

# Copy task coppies ONLY static assets like images into site build
copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks.
  assets:
    - "assets/**/*"
    # exclusions: (Don't copy these items because they are handled by other gulp tasks):
    - "!assets/{scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    #- "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running Copy"

# Main Gulp Sass task (for main.css).
sass:
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running KCC Theme Sass"
  src: "assets/scss/kcc-theme.scss"

# Gulp task to create stylesheet for custom options in CloudCannon (CMS customizations). Editors can use these styles as option in the CMS.
translateSass:
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running translateScss"
  src: "assets/scss/translate.scss"

jekyll:
  notification: "Running jekyll"

watch: # 'Watch' for changes in all the following:
  images:
    - "assets/img/**/*"
  sass: "assets/scss/**/*.scss"
  cmsScss: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}" # watch the project root.
    - "{_data,_hash,_includes,_layouts,_pages,_posts,_alerts,_accordions,_tabs}/**/*.{md,html,yml,xml}" # watch standard jekyll dirs.
    - "humans.txt"
    # !exlclusions:
    # These are important exceptions that should be excluded from watching!
    - "!sitemap.xml" # When you run `$ gulp --production`, sitemap gets copied-out to project root. This would then, be picked up by watch, which would kick-off another build, causing another change in the sitemap.xml file (i.e. an infinite loop)
    - "!_site/**/*" # This is always going to change.
    - "!assets/**/*" # Don't watch 'assets/' dir. SASS & JS changes get injected into the '_site' dir & localhost:3000/ whithout having to re-run the whole 'build' task. Images are watched seperately
